### PR TITLE
Initial Example Repository

### PR DESCRIPTION
**Pull request by WardLT**
This PR adds the submission script for JARVIS to the examples repository.

### CODE REVIEW

**Comment by jgaff** [comment]
As discussed, holding off on merging this until we get the JARVIS submission where we want it.

**Comment by blaiszik** [comment]
I see this is a bit stale, how are things coming with JARVIS? What is holding this back? @WardLT @jgaff

**Comment by jgaff** [comment]
Given that we have tutorials for MDFCC now, is it important to have this example? I don't recall what blockers there were with the JARVIS example, but if there are still issues it might be better to skip it. Especially since a new user either can't or shouldn't submit JARVIS.

**Comment by WardLT** [comment]
I think the idea from this PR was to illustrate an example of how to push an existing database to Connect. The other thought was to put the code for harvesting different repos on GitHub so that we do not loose them. 

I was not sure what the issue was here either. I think it was something around the schema, maybe the use of a project block?

**Comment by jgaff** [comment]
Right, I think this was moved from `connect_server` where the harvesters lived. I wonder if `connect_client` is the right place for harvesters now, though? Maybe the new `mdf-examples` repo would be better suited to hosting the harvester code.

Yeah, looking over the notebook there are a bunch of `custom` block fields, including nested dictionaries. This example would definitely need updating, no matter where it ends up.

**Comment by WardLT** [comment]
`mdf-examples` sounds like a good home

**Pull request closed without merging**
